# Generated by Django 4.1.4 on 2022-12-26 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('closed_date', models.DateTimeField(blank=True)),
                ('closed', models.BooleanField(default=False)),
                ('opener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='WalTalKie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_code', models.SmallIntegerField(default=0)),
                ('qr_code', models.CharField(max_length=200)),
                ('event', models.ManyToManyField(blank=True, to='warehouse.event')),
                ('model_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.modelproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('rea_date', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('opener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('qr_code', models.CharField(max_length=250)),
                ('came_out_date', models.DateField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.modelproduct')),
                ('reason', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.reason')),
            ],
        ),
    ]
