# Generated by Django 4.1.4 on 2022-12-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_depot_came_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.reason'),
        ),
    ]
