# Generated by Django 4.1.4 on 2022-12-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_depot_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='name',
        ),
    ]
