# Generated by Django 4.1.4 on 2022-12-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
