# Generated by Django 4.1.4 on 2022-12-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_event_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='waltalkie',
            name='warehouse',
            field=models.BooleanField(default=True),
        ),
    ]
