# Generated by Django 4.1.4 on 2022-12-29 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
