# Generated by Django 4.1.4 on 2022-12-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_appeal_close_date_appeal_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
