# Generated by Django 4.1.4 on 2022-12-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_appeal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
