# Generated by Django 4.1.4 on 2023-01-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_alter_appeal_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
